enable-on-join: true
allow-looting: true
create-armor-stand: true
enabled-worlds:
  - 'world'
  - 'test'

liftable-entities:
  - 'ALL_ANIMALS'
  - 'VILLAGER'

messages:
  usage: '<gray>错误的用法: 请使用<gold>/ep [reload|toggle]'
  player-command: '<gray>此命令只能由玩家执行'
  no-permission: '<red>你没有权限使用此命令'
  reloaded: '<gray>重载完成'
  enabled: '已开启举起实体功能'
  disabled: '已关闭举起实体功能'
  lifted: '已举起生物，Shift放下，Shift+左键抛出，Shift+右键放置'
  dropped: '已放下生物'
  tossed: '已抛出生物'
  placed: '已将生物放置'
  lifting-entity-dead: '举着的生物死掉啦'
  other-looted: '举着的生物被{0}抢走啦'
  looted: '你抢走了{0}的生物'
  has-porter: '这个生物已经被{0}举起啦'

support:
  bentobox:
    flag-name: 举起或放下实体
    flag-description: 是否允许举起或放下实体
    no-permission: '<gray>[<aqua>岛屿<gray>] <red>岛屿保护: 你没有权限举起或放下实体'
